#ifndef PS_CONSOLE_CLASSIC_TEX_H
#define PS_CONSOLE_CLASSIC_TEX_H

#include <stdint.h>

/* Generated by tools/glb2console.py - see ps_console_classic.h.
 *
 * Kept in its own translation unit rather than as a static array in
 * a header so that including it from more than one place cannot
 * silently duplicate 64 KB of texture in a 2 MB console. */
#define PS_CONSOLE_CLASSIC_TEX_WIDTH  256
#define PS_CONSOLE_CLASSIC_TEX_HEIGHT 256
#define PS_CONSOLE_CLASSIC_CLUT_COLORS 256

extern const uint16_t psConsoleClassicTextureData[];
extern const uint16_t psConsoleClassicClutData[];

#endif // PS_CONSOLE_CLASSIC_TEX_H
